### ISSUE TITLE
Multiple menu items?

### ISSUE THREAD

**Issue by fdncred** [heku/Kool.EditProject#1]
Any idea how to get rid of one of these menu items for your extension?
![devenv_2018-10-30_07-15-29](https://user-images.githubusercontent.com/343840/47717443-c2790300-dc13-11e8-822f-b3bde02bbf8c.png)

**Comment by fdncred** [comment]
I wonder if this could have anything to do with MultiTargeting? The project that the screenshot is made from targets multiple frameworks.
```xml
    <TargetFrameworks>netstandard2.0;net472</TargetFrameworks>
```
But I have other projects that are "normal" single target projects and they only have 1 context menu item.

Maybe that's a clue on how to solve the problem.

Thanks,
Darren

**Comment by heku** [comment]
Thx for  your feedback, I will look into it.

**Comment by heku** [comment]
Thank you again for your feedback, after a few [research](https://developercommunity.visualstudio.com/content/problem/312523/envdteprojectkind-no-longer-differentiates-between.html), I believe this issue is because the Visual Studio team changed the dotnet core project metadata since 15.8, I've fixed this issue on dev branch, could you please try the last dev branch [build](https://ci.appveyor.com/project/heku/kool-editproject/branch/dev/artifacts) and let me know if your issue is fixed. I will merge it to master and publish to marketplace if it works.

**Comment by fdncred** [comment]
Looks good. Thanks for the fix!
